# Generated by Django 3.2.6 on 2022-01-08 04:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='userdetails',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Email', models.EmailField(max_length=254)),
                ('Username', models.CharField(max_length=20)),
                ('Password', models.CharField(max_length=8)),
            ],
        ),
    ]
